config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inflows
  resources :setups
  resources :settings
  resources :habbits
  resources :systems
  resources :traffics
  resources :companies
  resources :countries do
  	member do
    	get 'buys_from'
      get 'buys_from_countries'
    	get 'internal_turnover'
    	get 'foreign_buyers'
      get 'payment_systems'
  	end
  end
  resources :websites

  root :to => 'websites#index'
  get 'indonesia', to: 'scrypt#indonesia'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :traffics
  	has_many :websites, through: :traffics
  	has_many :habbits
  	# has_many :local_websites, through: :traffics, :class_name => "Website", :foreign_key => "mother_country_id"
  	# has_many :local_websites, :class_name => "Website", :foreign_key => "mother_country_id"

end

app/models/habbit.rb
class Habbit < ApplicationRecord
  belongs_to :country
  belongs_to :system
end

app/models/inflow.rb
class Inflow < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/setup.rb
class Setup < ApplicationRecord
  belongs_to :website
end

app/models/system.rb
class System < ApplicationRecord
	has_many :habbits
	enum payment_type: [ 'International cards', 'Local cards', 'Online banking', 'E-wallets', 'Prepaid', 'Encashment', 'Cash on delivery']
	enum source_type: ['Adyen', 'Worldpay', 'Xsolla', 'YM', 'Other']
end

app/models/traffic.rb
class Traffic < ApplicationRecord
  belongs_to :country
  belongs_to :website
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :email, :presence => true, :email => true
  
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :country
  belongs_to :company, optional: true
  has_many :traffics, dependent: :destroy
  has_many :countries, through: :traffics
  has_one :setup, dependent: :destroy

  enum category: [ 'Marketplace', 'Electronics', 'Apparel', 'Classifieds', 'Gazette', 'Webservice', 'Food', 'Communications', 'Media', 'Aggregator', 'News', 'Adult', 'Exchange', 'Betting', 'Casino', 'Coupon', 'Tickets', 'Auction', 'Other']
  enum status: [ 'Invalid', 'Awaiting', 'Pipelined', 'Underway', 'Boarded']

  after_create :generate_setup
  after_update :renew_traffic



  def generate_setup
  	setting = Setting.last
  	Setup.create(website_id: self.id, conversion: setting.conversion, average_bill: setting.average_bill, yandex_net_fee: setting.yandex_net_fee, yandex_share: setting.yandex_share)
  end

  def renew_traffic
    self.traffics.each do |traffic|
      unless traffic.mother_country_id == self.country_id
        traffic.update!(mother_country_id: self.country_id)
      end
    end
  end

end

app/controllers/websites_controller.rb
require 'builder'
require 'will_paginate'

class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.paginate(:page => params[:page], :per_page => 30).order("monthly_visits DESC")
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @traffics = @website.traffics.order("country_share desc")

  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:country_id, :url, :company_id, :category, :description, :contacts, :monthly_visits, :country_rank, :valid_for_yandex, :status, :bounce_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/habbits_helper.rb
module HabbitsHelper
end

app/helpers/inflows_helper.rb
module InflowsHelper
end

app/helpers/scrypt_helper.rb
module ScryptHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/traffics_helper.rb
module TrafficsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_form.html.erb
<%= simple_form_for @website do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.association :country %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :website_url %>
  </div>



<!--   <div class="field">
    <%= form.association :company, id: :website_company_id %>
  </div> -->

  <div class="field">
    <%= form.input :category, collection: Website.categories.keys %>
  </div>

  <div class="field">
    <%= form.input :status, collection: Website.statuses.keys %>
  </div>

  <div class="field">
    <%= form.label :description %>
      <%= form.text_area :description, id: :website_description %> 

  </div>

  <div class="field">
    <%= form.label :contacts %>
    <%= form.text_area :contacts, id: :website_contacts %>
  </div>

  <div class="field">
    <%= form.label "Monthly visits" %>
    <%= form.number_field :monthly_visits, id: :website_monthly_visits %>
  </div>

<!--   <div class="field">
    <%= form.label :country_rank %>
    <%= form.number_field :country_rank, id: :website_country_rank %>
  </div> -->

  <div class="field">
    <%= form.label :valid_for_yandex %>
    <%= form.check_box :valid_for_yandex, id: :website_valid %>
  </div>

  

 <!--  <div class="field">
    <%= form.label :bounce_rate %>
    <%= form.number_field :bounce_rate, id: :website_bounce_rate %>
  </div> -->

  <div class="form-actions col-sm-offset-3">
    <%= form.button :submit %>
  </div>

  
<% end %>

app/views/websites/_list.html.erb
<%# app/views/students/_list.html.erb %>
<div id="filterrific_results">

  <div>
    <%= page_entries_info websites # provided by will_paginate %>
  </div>

  <table>
    <tr>
      <th>URL</th>
      <th>Country</th>
      <th>Registered at</th>
    </tr>
    <% websites.each do |website| %>
      <tr>
        <td><%= link_to(website.url, website_path(website)) %></td>
        <td><%= website.country.name %></td>
        <td><%= website.decorated_created_at %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate websites # provided by will_paginate %>

app/views/websites/edit.html.erb
<div class="container">

<div class="row">
<div class="col-md-6">

<h3>Editing website</h3>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>


</div>
</div>
</div>

app/views/websites/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1> <%= "Websites list (#{Website.all.length})" %></h1>
<%= image_tag('/images/target.svg', :class => "globe") %>



<div class="btn">
  <%= link_to '+ website', new_website_path  %>
</div>

<table class="table table-nonfluid">
  <thead>
    <tr>
      <th>Country</th>
      <th>URL</th>
      <th>Monthly visits</th>
      <th>Category</th>
      <th>Valid</th>
      <th>Status</th>
   <!--    <th>Description</th>
      <th>Contacts</th>
      <th>Monthly visits</th>
      <th>Country rank</th> -->
<!--       <th>Valid</th>
 -->    <!--   <th>Status</th>
      <th>Bounce rate</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= link_to website.country.name, website.country, :class=>"country_link" %></td>
        <b>
        <td><b><%= link_to website.url, website %></b></td>
        <%- if website.monthly_visits %>
          <td><%= (website.monthly_visits/1000) %>K</td>
        <%- else %>
          <td></td>
        <%- end %>
        <td><b><%= website.category %></b></td>

        <%- if website.valid_for_yandex == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>


        <td><b><%= website.status %></b></td>

<!--         <td><%= website.company %></td>
 -->        <!-- <td><%= website.category %></td> -->
      <td><%= @info %></td>
       <!--  <td><%= website.description %></td>
        <td><%= website.contacts %></td>
        <td><%= website.monthly_visits %></td>
        <td><%= website.country_rank %></td>
        <td><%= website.valid_for_yandex %></td>
        <td><%= website.status %></td>
        <td><%= website.bounce_rate %></td> -->
<!--         <td><%= link_to 'Показать', website %></td>
 -->    
        <td> 
        <%= link_to edit_website_path(website) do %>
          <%= image_tag '/images/pencil.svg', :class => "success" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @websites %>

<br>

</div>

app/views/websites/new.html.erb
<div class="container">

<div class="row">
<div class="col-md-6">	
	
<h3>New Website</h3>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>
</div>
</div>
</div>

app/views/websites/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to '<< back', websites_path %>

<br>
<br>

<div class="colored_heading">
<h3><%= @website.url %></h3>
</div>

<br>

<table class="table table-nonfluid">
  <thead>
    <tr>
      <th>Country of presence</th>
      <th>Monthly visits</th>
      <th>Category</th>
<!--       <th>Company</th>
 -->      
      <th>Country rank</th>
      <th>Valid</th>
      <th>Status</th>
      <!-- <th>Bounce rate</th> -->
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @website.country.name %></td>
        
        <%- if @website.monthly_visits %>
          <td><%= @website.monthly_visits/1000%>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <td><%= @website.category %></td>
        
   <!--      <%- if @website.company %>
          <td>$<%= @website.company.name %></td>
        <%- else %>
          <td></td>
        <%- end %> -->

        
        <td><%= @website.country_rank %></td>

        <%- if @website.valid_for_yandex == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>


        <td><%= @website.status %></td>
        <!-- <td><%= @website.bounce_rate %></td> -->


        <td> 
        <%= link_to edit_website_path(@website) do %>
          <%= image_tag '/images/pencil.svg', :class => "success" %>
        <% end %>
        </td>

        <td><%= link_to 'Delete', @website, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  </tbody>
</table>

<br>
</div>

<div class="show_more_block">
  <a class="more" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Contacts & more
  </a>
</div>

<div class="collapse" id="collapseExample">
  <div class="card card-block">
    <b> Contacts: </b> <%= @website.contacts %>
    <br>
    <br>
    <b> More info: </b> <%= @website.description %>
  </div>
</div>



<h5><%= "Traffic of" + " " + @website.url + " " + "by countries" %></h5>


<%= simple_form_for Traffic.new do |form| %>
  
  <ul>
    <li>
      <div class="field">
        <%= form.association :country %>
      </div>
    </li>

  <%= form.hidden_field :website_id, value: @website.id  %>
  <%= form.hidden_field :mother_country_id, value: @website.country.id  %>


<li>
  <div class="field">
    <%= form.label :country_share %>
    <%= form.number_field :country_share, id: :traffic_country_share %>
  </div>
</li>

<li>
  <div class="form-actions col-sm-offset-3">
    <%= form.button :submit %>
  </div>
</li>

</ul>

<% end %>





<table class="table table-nonfluid footer">

  <thead>
    <tr>
      <th>Country</th>
      <th>Country share</th>
      <th>Yearly visits</th>
      <th>Annual turnover ($30)</th>
      <th>Fee (0.11%)</th>
     <!--  <th>Country visits</th>
      <th>Bounce rate</th>
      <th>Country visitors</th>
      <th>Annual turnover</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffics.each do |traffic| %>
      <tr>
        <td><%= link_to traffic.country.name, traffic.country %></td>
        <%- if traffic.country_share %>
        <td><%= (traffic.country_share*100).round(2) %>%</td>
        <% end %>

        <%- if traffic.website.monthly_visits %>
          <%- @country_visits = ((traffic.website.monthly_visits*12*traffic.country_share)/1000).round %>
          <td><%= @country_visits %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <%- if @country_visits && traffic.website.setup %>
          <td>$<%= (@country_visits*traffic.website.setup.average_bill*traffic.website.setup.conversion).round %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <%- if @country_visits && traffic.website.setup %>
          <td>$<%= (@country_visits*traffic.website.setup.average_bill*traffic.website.setup.conversion*Setting.last.yandex_net_fee).round  %>K</td>
        <%- else %>
          <td></td>
        <%- end %>


<!-- 


        <%- if traffic.country_visits %>
          <td><%= traffic.country_visits/1000000 %>mln</td>
        <% else %>
          <td>mln</td>
        <% end %>

        <%- if traffic.annual_turnover %>
        <td>$<%= traffic.annual_turnover/1000000 %>mln</td>
        <% else %>
          <td>$</td>
        <% end %>

        <%- if traffic.annual_turnover %>
          <td>$<%= ((traffic.annual_turnover/1000)*Setting.last.yandex_net_fee).round %>K</td>
        <% else %>
          <td>$</td>
        <% end %> -->

        
        <td> 
        <%= link_to edit_traffic_path(traffic) do %>
          <%= image_tag '/images/pencil.svg', :class => "success" %>
        <% end %>
        </td>

        <td><%= link_to 'X', traffic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>