config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inflows
  resources :setups
  resources :settings
  resources :habbits
  resources :systems
  resources :traffics
  resources :companies
  resources :countries do
  	member do
    	get 'buys_from'
      get 'buys_from_countries'
    	get 'internal_turnover'
    	get 'foreign_buyers'
      get 'payment_systems'
  	end
  end
  resources :websites

  root :to => 'websites#index'
  get 'indonesia', to: 'scrypt#indonesia'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :traffics
  	has_many :websites, through: :traffics
  	has_many :habbits
  	# has_many :local_websites, through: :traffics, :class_name => "Website", :foreign_key => "mother_country_id"
  	# has_many :local_websites, :class_name => "Website", :foreign_key => "mother_country_id"

end

app/models/habbit.rb
class Habbit < ApplicationRecord
  belongs_to :country
  belongs_to :system
end

app/models/inflow.rb
class Inflow < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/setup.rb
class Setup < ApplicationRecord
  belongs_to :website
end

app/models/system.rb
class System < ApplicationRecord
	has_many :habbits
	enum payment_type: [ 'International cards', 'Local cards', 'Online banking', 'E-wallets', 'Prepaid', 'Encashment', 'Cash on delivery']
	enum source_type: ['Adyen', 'Worldpay', 'Xsolla', 'YM', 'Other']
end

app/models/traffic.rb
class Traffic < ApplicationRecord
  belongs_to :country
  belongs_to :website
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :email, :presence => true, :email => true
  
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :country
  belongs_to :company, optional: true
  has_many :traffics, dependent: :destroy
  has_many :countries, through: :traffics
  has_one :setup, dependent: :destroy

  enum category: [ 'Marketplace', 'Electronics', 'Apparel', 'Classifieds', 'Gazette', 'Webservice', 'Food', 'Communications', 'Media', 'Aggregator', 'News', 'Adult', 'Exchange', 'Betting', 'Casino', 'Coupon', 'Tickets', 'Auction', 'Other']
  enum status: [ 'Invalid', 'Awaiting', 'Pipelined', 'Underway', 'Boarded']

  after_create :generate_setup
  after_update :renew_traffic



  def generate_setup
  	setting = Setting.last
  	Setup.create(website_id: self.id, conversion: setting.conversion, average_bill: setting.average_bill, yandex_net_fee: setting.yandex_net_fee, yandex_share: setting.yandex_share)
  end

  def renew_traffic
    self.traffics.each do |traffic|
      unless traffic.mother_country_id == self.country_id
        traffic.update!(mother_country_id: self.country_id)
      end
    end
  end

end

app/controllers/traffics_controller.rb
class TrafficsController < ApplicationController
  before_action :set_traffic, only: [:show, :edit, :update, :destroy]

  # GET /traffics
  # GET /traffics.json
  def index
    @traffics = Traffic.all
  end

  # GET /traffics/1
  # GET /traffics/1.json
  def show
  end

  # GET /traffics/new
  def new
    @traffic = Traffic.new
  end

  # GET /traffics/1/edit
  def edit
  end

  # POST /traffics
  # POST /traffics.json
  def create
    @traffic = Traffic.new(traffic_params)

    respond_to do |format|
      if @traffic.save
        format.html { redirect_to @traffic.website, notice: 'Traffic was successfully created.' }
        format.json { render :show, status: :created, location: @traffic }
      else
        format.html { render :new }
        format.json { render json: @traffic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traffics/1
  # PATCH/PUT /traffics/1.json
  def update
    respond_to do |format|
      if @traffic.update(traffic_params)
        format.html { redirect_to @traffic.website, notice: 'Traffic was successfully updated.' }
        format.json { render :show, status: :ok, location: @traffic }
      else
        format.html { render :edit }
        format.json { render json: @traffic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffics/1
  # DELETE /traffics/1.json
  def destroy
    @traffic.destroy
    respond_to do |format|
      format.html { redirect_to @traffic.website, notice: 'Traffic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traffic
      @traffic = Traffic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traffic_params
      params.require(:traffic).permit(:country_id, :website_id, :country_share, :country_visits, :bounce_rate, :country_visitors, :annual_turnover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/habbits_helper.rb
module HabbitsHelper
end

app/helpers/inflows_helper.rb
module InflowsHelper
end

app/helpers/scrypt_helper.rb
module ScryptHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/traffics_helper.rb
module TrafficsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/traffics/_form.html.erb
<%= simple_form_for @traffic do |form| %>
  <% if traffic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(traffic.errors.count, "error") %> prohibited this traffic from being saved:</h2>

      <ul>
      <% traffic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.association :country %>
  </div>

  <div class="field">
    <%= form.association :website, label_method: :url  %>
  </div>

  <div class="field">
    <%= form.label :country_share %>
    <%= form.number_field :country_share, id: :traffic_country_share %>
  </div>

  <div class="field">
    <%= form.label :country_visits %>
    <%= form.number_field :country_visits, id: :traffic_country_visits %>
  </div>

  <div class="field">
    <%= form.label :bounce_rate %>
    <%= form.number_field :bounce_rate, id: :traffic_bounce_rate %>
  </div>

  <div class="field">
    <%= form.label :country_visitors %>
    <%= form.number_field :country_visitors, id: :traffic_country_visitors %>
  </div>

  <div class="field">
    <%= form.label :annual_turnover %>
    <%= form.number_field :annual_turnover, id: :traffic_annual_turnover %>
  </div>

  <div class="form-actions col-sm-offset-3">
    <%= form.button :submit %>
  </div>

<% end %>

app/views/traffics/edit.html.erb
<h1>Editing Traffic</h1>

<%= render 'form', traffic: @traffic %>

<%= link_to 'Show', @traffic %> |
<%= link_to 'Back', traffics_path %>

app/views/traffics/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Traffics</h1>

<table class="table table-nonfluid">

  <thead>
    <tr>
      <th>Country</th>
      <th>Website</th>
      <th>Country share</th>
     <!--  <th>Country visits</th>
      <th>Bounce rate</th>
      <th>Country visitors</th>
      <th>Annual turnover</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffics.each do |traffic| %>
      <tr>
        <td><%= traffic.country.name %></td>
        <td><%= traffic.website.url %></td>
        <td><%= traffic.country_share %>%</td>
       <!--  <td><%= traffic.country_visits %></td>
        <td><%= traffic.bounce_rate %></td>
        <td><%= traffic.country_visitors %></td>
        <td><%= traffic.annual_turnover %></td> -->
        <td><%= link_to 'Show', traffic %></td>
        <td><%= link_to 'Edit', edit_traffic_path(traffic) %></td>
        <td><%= link_to 'Destroy', traffic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traffic', new_traffic_path %>
</div>

app/views/traffics/new.html.erb
<div class="container">

<h1>New Traffic</h1>

<%= render 'form', traffic: @traffic %>

<%= link_to 'Back', traffics_path %>

</div>

app/views/traffics/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @traffic.country %>
</p>

<p>
  <strong>Website:</strong>
  <%= @traffic.website %>
</p>

<p>
  <strong>Country share:</strong>
  <%= @traffic.country_share %>
</p>

<p>
  <strong>Country visits:</strong>
  <%= @traffic.country_visits %>
</p>

<p>
  <strong>Bounce rate:</strong>
  <%= @traffic.bounce_rate %>
</p>

<p>
  <strong>Country visitors:</strong>
  <%= @traffic.country_visitors %>
</p>

<p>
  <strong>Annual turnover:</strong>
  <%= @traffic.annual_turnover %>
</p>

<%= link_to 'Edit', edit_traffic_path(@traffic) %> |
<%= link_to 'Back', traffics_path %>

</div>