config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inflows
  resources :setups
  resources :settings
  resources :habbits
  resources :systems
  resources :traffics
  resources :companies
  resources :countries do
  	member do
    	get 'buys_from'
      get 'buys_from_countries'
    	get 'internal_turnover'
    	get 'foreign_buyers'
      get 'payment_systems'
  	end
  end
  resources :websites

  root :to => 'websites#index'
  get 'indonesia', to: 'scrypt#indonesia'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :traffics
  	has_many :websites, through: :traffics
  	has_many :habbits
  	# has_many :local_websites, through: :traffics, :class_name => "Website", :foreign_key => "mother_country_id"
  	# has_many :local_websites, :class_name => "Website", :foreign_key => "mother_country_id"

end

app/models/habbit.rb
class Habbit < ApplicationRecord
  belongs_to :country
  belongs_to :system
end

app/models/inflow.rb
class Inflow < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/setup.rb
class Setup < ApplicationRecord
  belongs_to :website
end

app/models/system.rb
class System < ApplicationRecord
	has_many :habbits
	enum payment_type: [ 'International cards', 'Local cards', 'Online banking', 'E-wallets', 'Prepaid', 'Encashment', 'Cash on delivery']
	enum source_type: ['Adyen', 'Worldpay', 'Xsolla', 'YM', 'Other']
end

app/models/traffic.rb
class Traffic < ApplicationRecord
  belongs_to :country
  belongs_to :website
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :email, :presence => true, :email => true
  
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :country
  belongs_to :company, optional: true
  has_many :traffics, dependent: :destroy
  has_many :countries, through: :traffics
  has_one :setup, dependent: :destroy

  enum category: [ 'Marketplace', 'Electronics', 'Apparel', 'Classifieds', 'Gazette', 'Webservice', 'Food', 'Communications', 'Media', 'Aggregator', 'News', 'Adult', 'Exchange', 'Betting', 'Casino', 'Coupon', 'Tickets', 'Auction', 'Other']
  enum status: [ 'Invalid', 'Awaiting', 'Pipelined', 'Underway', 'Boarded']

  after_create :generate_setup
  after_update :renew_traffic



  def generate_setup
  	setting = Setting.last
  	Setup.create(website_id: self.id, conversion: setting.conversion, average_bill: setting.average_bill, yandex_net_fee: setting.yandex_net_fee, yandex_share: setting.yandex_share)
  end

  def renew_traffic
    self.traffics.each do |traffic|
      unless traffic.mother_country_id == self.country_id
        traffic.update!(mother_country_id: self.country_id)
      end
    end
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy, :buys_from, :internal_turnover, :foreign_buyers, :payment_systems, :buys_from_countries]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.paginate(:page => params[:page], :per_page => 30).order("sales_region ASC")
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @websites = Website.where(country_id: @country.id).order("monthly_visits DESC")
  end

  def buys_from
    # @websites = @country.websites.where.not(country_id: @country.id).order("monthly_visits DESC")
    @traffics = @country.traffics.where(country_id: @country.id).order("country_visits DESC").where.not(website_id: Website.where(country_id: @country.id))
  end

  def buys_from_countries
    # @websites = @country.websites.where.not(country_id: @country.id).order("monthly_visits DESC")
    @inflows = Inflow.where(importer_country_id: @country.id).order("annual_turnover DESC")
  end

  def foreign_buyers
      @inflows = Inflow.where(exporter_country_id: @country.id).order("annual_turnover DESC")
  end

  def internal_turnover
    @traffics = @country.traffics.where(country_id: @country.id, mother_country_id: @country.id).order("country_visits DESC")
  end

  def payment_systems
    @system = System.new
    @habbit = Habbit.new
    @habbits = @country.habbits
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :sales_region, :importer_region, :market_volume, :users, :shoppers, :game_market, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/habbits_helper.rb
module HabbitsHelper
end

app/helpers/inflows_helper.rb
module InflowsHelper
end

app/helpers/scrypt_helper.rb
module ScryptHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/traffics_helper.rb
module TrafficsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/countries/buys_from.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>

<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>

    <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>


<br>
<br>
<br>
<br>



<h5><%= "Where" + " " + @country.name + " " + "buys from"%></h5>

<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>Country</th>
      <th>URL</th>
      <th>Share</th>
<!--       <th>Country visits (yearly)</th>
 -->      <th>Turnover (yearly)</th>
      <th>Fee (0.1%)</th>
      <th>Category</th>
      <th>Status</th>
   <!--    <th>Description</th>
      <th>Contacts</th>
      <th>Monthly visits</th>
      <th>Country rank</th> -->
<!--       <th>Valid</th>
 -->    <!--   <th>Status</th>
      <th>Bounce rate</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffics.each do |traffic| %>
      <tr>
        <td><b><%= link_to traffic.website.country.name, traffic.website.country %></b></td>
        <td><b><%= link_to traffic.website.url, traffic.website %></b></td>
        <td><b><%= (traffic.country_share*100).round(2) %></b>%</td>
        
       <!--  <%- if traffic.website.monthly_visits %>
          <%- @country_visits = ((traffic.website.monthly_visits*12*(traffic.country_share))/1000).round %>
          <td><%= @country_visits %>K</td>
        <%- else %>
          <td></td>
        <%- end %> -->

        <%- if @country_visits && traffic.website.setup %>
          <td>$<%= (@country_visits*traffic.website.setup.average_bill*traffic.website.setup.conversion).round %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <%- if @country_visits && traffic.website.setup %>
          <td>$<%= (@country_visits*traffic.website.setup.average_bill*traffic.website.setup.conversion*Setting.last.yandex_net_fee).round(2)  %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <td><b><%= traffic.website.category %></b></td>
        <td><b><%= traffic.website.status %></b></td>

      <td><%= @info %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/countries/buys_from_countries.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>



<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>


  <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>



<br>
<br>
<br>
<br>


<h5><%= "What countries" + " " + @country.name + " " + "buys from"%></h5>


<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>Country</th>
      <th>Annual turnover</th>
      <th>Fee (0.1%)</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <%- unless @inflows.length == 0  %>
          <%- @inflows.each do |inflow|  %>
            <tr>
              <td><%= link_to Country.where(id: inflow.exporter_country_id).take.name, Country.where(id: inflow.exporter_country_id).take %></td>
              <td>$<%= inflow.annual_turnover/1000000 %> mln</td>
              <td>$<%= ((inflow.annual_turnover*Setting.last.yandex_net_fee)/1000).round %>K</td>
            </tr>
          <% end%>
        <% end%>
  </tbody>
</table>

<br>

app/views/countries/edit.html.erb
<div class="container">

<div class="row">
<div class="col-md-6">

<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>
</div>
</div>
</div>

app/views/countries/foreign_buyers.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>



<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>



<br>
<br>
<br>
<br>


<h5><%= "Who buys from" + " " + @country.name%></h5>


<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>Country</th>
      <th>Annual turnover</th>
      <th>Fee (0.1%)</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <%- unless @inflows.length == 0  %>
          <%- @inflows.each do |inflow|  %>
            <tr>
              <td><%= link_to Country.where(id: inflow.importer_country_id).take.name, Country.where(id: inflow.importer_country_id).take %></td>
              <td>$<%= inflow.annual_turnover/1000000 %> mln</td>
              <td>$<%= ((inflow.annual_turnover*Setting.last.yandex_net_fee)/1000).round %>K</td>
            </tr>
          <% end%>
        <% end%>
  </tbody>
</table>

<br>

app/views/countries/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Countries</h1>
<%= image_tag('/images/globe.svg', :class => "globe") %>

<div class="btn">
  <%= link_to '+ country', new_country_path  %>
</div>

<table class="table table-nonfluid">
  <thead>
    <tr>
      <th>Country</th>
      <th>E-commerce volume</th>
      <th>Internet audience</th>
      <th>e-shoppers</th>
      <th>Game market</th>
      <th>Sales region</th>
      <th>Importer country</th>
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td ><%= link_to country.name, country %></td>
        <%- if country.market_volume %>
          <td>$<%= country.market_volume/1000000000 %>bn</td>
        <%- else%>
          <td> </td>
        <% end %>

        <%- if country.users %>
          <td><%= country.users/1000000 %>mln</td>
        <%- else%>
          <td> </td>
        <% end %>

        <%- if country.shoppers %>
          <td><%= country.shoppers/1000000 %>mln</td>
        <%- else%>
          <td> </td>
        <% end %>

        <%- if country.game_market %>
          <td><%= country.game_market/1000000 %>mln</td>
        <%- else%>
          <td> </td>
        <% end %>


        <%- if country.sales_region == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>
         <%- if country.importer_region == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>
        
        <td> 
        <%= link_to edit_country_path(country) do %>
          <%= image_tag '/images/pencil.svg', :class => "success" %>
        <% end %>
        </td>
<!--         <td><%= link_to 'Удалить', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 -->      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @countries %>

</div>

app/views/countries/internal_turnover.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>

<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>


  <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>


<br>
<br>
<br>
<br>



<h5><%= "Internal traffic of" + " " + @country.name%></h5>

<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>Country</th>
      <th>URL</th>
      <th>Monthly country visits</th>
      <th>Turnover</th>
      <th>Category</th>
      <th>Status</th>
   <!--    <th>Description</th>
      <th>Contacts</th>
      <th>Monthly visits</th>
      <th>Country rank</th> -->
<!--       <th>Valid</th>
 -->    <!--   <th>Status</th>
      <th>Bounce rate</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffics.each do |traffic| %>
      <tr>
        <td><b><%= traffic.website.country.name %></b></td>
        <td><b><%= link_to traffic.website.url, traffic.website %></b></td>
        <%- if traffic.website.monthly_visits %>
          <%- @country_visits = (traffic.website.monthly_visits/1000*(traffic.country_share)).round %>
          <td><%= @country_visits %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <%- if @country_visits && traffic.website.setup %>
          <td>$<%= (@country_visits*traffic.website.setup.average_bill*traffic.website.setup.conversion).round  %>K</td>
        <%- else %>
          <td></td>
        <%- end %>

        <td><b><%= traffic.website.category %></b></td>
        <td><b><%= traffic.website.status %></b></td>

      <td><%= @info %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/countries/new.html.erb
<div class="container">

<div class="row">
<div class="col-md-6">

<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

</div>
</div>
</div>

app/views/countries/payment_systems.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>
<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>

<br>
<br>
<br>
<br>


<h5><%= "How people pay in" + " " + @country.name + " " + "(Adyen)"%></h5>



<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Share</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habbits.each do |habbit| %>

      <tr>
        <td><b><%= link_to habbit.system.name, habbit.system %></b></td>
        <td><b><%= habbit.system.payment_type %></b></td>
        <td><b><%= habbit.share %></b>%</td>
        <td><b><%= habbit.description %></b></td>
  
        <td><%= link_to 'Edit', edit_habbit_path(habbit) %></td>
        <td><%= link_to 'X', habbit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

</div>



<h6> Add new system </h6>


<%= simple_form_for System.new do |form| %>
  
  <ul>
    <li>
      <div class="field">
        <%= form.input :name %>
      </div>
    </li>

    <li>
      <div class="field">
        <%= form.input :payment_type, collection: System.payment_types.keys %>
      </div>
    </li>

     <li>
      <div class="field">
        <%= form.input :source_type, collection: System.source_types.keys %>
      </div>
    </li>

<li>
  <div class="form-actions col-sm-offset-3">
    <%= form.button :submit %>
  </div>
</li>

</ul>

<% end %>


<br>
<br>
<br>
<br>
<br>

<h6> Link system to the country</h6>


<%= simple_form_for Habbit.new do |form| %>
  
  <%= form.hidden_field :country_id, value: @country.id  %>

  <ul>
    
    <li>
      <div class="field">
        <%= form.association :system %>
      </div>
    </li>

    <li>
      <div class="field">
        <%= form.input :share %>
      </div>
    </li>

<li>
  <div class="form-actions col-sm-offset-3">
    <%= form.button :submit, "Link" %>
  </div>
</li>

</ul>

<% end %>

app/views/countries/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Back to country list', countries_path %>

<br>
<br>

<div class="colored_heading">
<h1><%= @country.name %></h1>
</div>

<br>
<ul class="mininav">
  <li class="mininav_link" > 
      <%= link_to "Top websites", country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Top importers", foreign_buyers_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (websites)", buys_from_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Buys from (countries)", buys_from_countries_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Internal market", internal_turnover_country_path(@country), :class=>"nav-link"  %>
  </li>

  <li class="mininav_link" > 
      <%= link_to "Payment systems", payment_systems_country_path(@country), :class=>"nav-link"  %>
  </li>

</ul>

<br>
<br>
<br>
<br>


<table class="table table-nonfluid">
  <thead>
    <tr>
      <th>E-commerce volume</th>
      <th>Internet audience</th>
      <th>E-shoppers</th>
      <th>Game market</th>
      <th>Sales region</th>
      <th>Importer country</th>
   <!--    <th>Description</th>
      <th>Contacts</th>
      <th>Monthly visits</th>
      <th>Country rank</th> -->
<!--       <th>Valid</th>
 -->    <!--   <th>Status</th>
      <th>Bounce rate</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <%- if @country.market_volume %>
          <td><%= @country.market_volume/1000000000 %>bn</td>
        <%- else %>
          <td></td>
        <%- end %>


        <%- if @country.users %>
          <td><%= @country.users/1000000 %>mln</td>
        <%- else %>
          <td></td>
        <%- end %>


        <%- if @country.shoppers %>
          <td><%= @country.shoppers/1000000 %>mln</td>
        <%- else %>
          <td></td>
        <%- end %>


        <%- if @country.game_market %>
          <td><%= @country.game_market/1000000 %>mln</td>
        <%- else %>
          <td></td>
        <%- end %>

        <%- if @country.sales_region == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>

         <%- if @country.importer_region == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>

        <td> 
        <%= link_to edit_country_path(@country) do %>
          <%= image_tag '/images/pencil.svg', :class => "success" %>
        <% end %>
        </td>
      </tr>
  </tbody>
</table>

<br>

<div class="show_more_block">
  <a class="more" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    More info
  </a>
</div>

<div class="collapse" id="collapseExample">
  <div class="card card-block">
    <%= @country.description %>
  </div>
</div>


<h5><%= "Top e-commerce websites in" + " " + @country.name + " " + "(#{Website.where(country_id: @country.id).length})" %></h5>

<div class="btn">
  <%= link_to '+ website', new_website_path  %>
</div>

<table class="table table-nonfluid footer">
  <thead>
    <tr>
      <th>URL</th>
      <th>Monthly visits</th>
      <th>Category</th>
      <th>Valid</th>
      <th>Status</th>
   <!--    <th>Description</th>
      <th>Contacts</th>
      <th>Monthly visits</th>
      <th>Country rank</th> -->
<!--       <th>Valid</th>
 -->    <!--   <th>Status</th>
      <th>Bounce rate</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>

        <td><b><%= link_to website.url, website %></b></td>
        <%- if website.monthly_visits %>
          <td><%= website.monthly_visits/1000 %>K</td>
        <%- else %>
          <td></td>
        <%- end %>
        <td><b><%= website.category %></b></td>
        <%- if website.valid_for_yandex == true %>
          <td> <%= image_tag('/images/success.svg', :class => "success") %> </td>
        <%- else%>
          <td> No </td>
        <% end %>
        <td><b><%= website.status %></b></td>

<!--         <td><%= website.company %></td>
 -->        <!-- <td><%= website.category %></td> -->
      <td><%= @info %></td>
       <!--  <td><%= website.description %></td>
        <td><%= website.contacts %></td>
        <td><%= website.monthly_visits %></td>
        <td><%= website.country_rank %></td>
        <td><%= website.valid_for_yandex %></td>
        <td><%= website.status %></td>
        <td><%= website.bounce_rate %></td> -->
<!--         <td><%= link_to 'Показать', website %></td>
 -->        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>